openapi: '3.0.2'
info:
  title: Companies House Internal Oracle Query API
  version: '1.0'
servers:
  - url: http://localhost:18565
tags:
  - name: emergency-auth-code-officers
    description: company officers eligible for emergency auth code delivery
  - name: emergency-auth-code-efiling-status
    description: company efiling status determines whether the company has efiled within a predefined period (e.g 1 calendar month)
  - name: company-action-code
    description: current action code set against the company
  - name: scottish-bankrupt-officer-search
    description: search for a Scottish bankrupt officer
    
paths:
  /emergency-auth-code/company/{company_number}/eligible-officers:
    parameters:
      - $ref: '#/components/parameters/companyNumber'
      - $ref: '#/components/parameters/startIndex'
      - $ref: '#/components/parameters/itemsPerPage'
    get:
      tags:
        - emergency-auth-code-officers
      operationId: listCompanyOfficers
      summary: Get a list of the companies officers that are eligible for emergency auth code delivery
      responses:
        '200':
          description: A list of eligible officers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/companyOfficers'
        '401':
          description: Unauthorised
        '404':
          description: No eligible officers found
  /emergency-auth-code/company/{company_number}/eligible-officers/{officer_id}:
    parameters:
      - $ref: '#/components/parameters/companyNumber'
      - $ref: '#/components/parameters/officerId'
    get:
      tags:
        - emergency-auth-code-officers
      operationId: getCompanyOfficer
      summary: Get a specific company officer that is eligible for emergency auth code delivery
      responses:
        '200':
          description: An eligible officer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/companyOfficer'
        '401':
          description: Unauthorised
        '404':
          description: Not found
  /emergency-auth-code/company/{company_number}/efiling-status:
    parameters:
      - $ref: '#/components/parameters/companyNumber'
    get:
      tags:
        - emergency-auth-code-efiling-status
      operationId: getCompanyEFilingStatus
      summary: Get the status fo the eFiling status to determine whether a company is eligible for emergency auth code delivery
      responses:
        '200':
          description: The company eFiling status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/companyEFilingStatus'
        '401':
          description: Unauthorised
        '404':
          description: Not found
  /company/{company_number}/action-code:
    parameters:
      - $ref: '#/components/parameters/companyNumber'
    get:
      tags:
        - corporate-body-action-code
      operationId: getCompanyActionCode
      summary: Get the action code for the company
      responses:
        '200':
          description: The action code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/actionCode'
        '401':
          description: Unauthorised
        '404':
          description: Not found
  /officer-search/scottish-bankrupt-officers:
    get:
      tags:
        - scottish-bankrupt-officer-search
      operationId: searchScottishBankruptOfficer
      summary: Search for a Scottish bankrupt officer
      responses:
        '200':
          description: List of Scottish bankrupt officers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scottishBankruptOfficers'
        '404':
          description: No Scottish bankrupt officers found
components:
  schemas:
    companyOfficer:
      type: object
      required:
        - id
        - name
        - officer_role
        - date_of_birth
        - appointed_on
        - nationality
        - country_of_residence
        - occupation
        - usual_residential_address
      properties:
        id:
          type: string
          description: The id of the user
          readOnly: true
          example: abc123
        name:
          type: string
          description: The officers name
          example: Joe Bloggs
        officer_role:
          type: string
          enum:
            - "director"
          description: The officers role within the company. enum values may be expanded to a subset of `officer_role` mappings here https://github.com/companieshouse/api-enumerations/blob/master/constants.yml
          example: director
        date_of_birth:
          type: object
          description: The officers date of birth details
          $ref: '#/components/schemas/officerDOB'
        appointed_on:
          type: string
          format: date
          description: The date the officer was appointed to the company
          example: 2020-05-05
        nationality:
          type: string
          description: The officers nationality
          example: British
        country_of_residence:
          type: string
          description: The officers country of residence
          example: United Kingdom
        occupation:
          type: string
          description: The officers occupation
          example: Chartered Accountant
        usual_residential_address:
          type: object
          description: The officers URA
          $ref: '#/components/schemas/officerURA'
    officerDOB:
      type: object
      readOnly: true
      required:
        - month
        - year
      properties:
        month:
          type: string
          description: The officers month of birth
          readOnly: true
          example: "01"
        year:
          type: string
          description: The officers year of birth
          readOnly: true
          example: "1999"
    officerURA:
      type: object
      readOnly: true
      required:
        - id
        - premises
        - address_line_1
        - locality
        - postcode
      properties:
        id:
          type: string
          description: The internal id of the URA
          readOnly: true
          example: "24681012"
        po_box:
          type: string
          description: The  post-office box number
          readOnly: true
          example: "10"
        premises:
          type: string
          description: The property name or number
          readOnly: true
          example: "10"
        address_line_1:
          type: string
          description: The first line of the address
          readOnly: true
          example: "Crown Way"
        address_line_2:
          type: string
          description: The second line of the address
          readOnly: true
          example: "Maindy"
        locality:
          type: string
          description: The locality
          readOnly: true
          example: "Cardiff"
        region:
          type: string
          description: The region
          readOnly: true
          example: "Glamorgan"
        country:
          type: string
          description: The country
          readOnly: true
          example: "Wales"
        postcode:
          type: string
          description: The postal code
          readOnly: true
          example: "CF143UZ"
    companyOfficers:
      type: object
      required:
        - items_per_page
        - start_index
        - total_results
        - items
      properties:
        items_per_page:
          type: integer
          format: int64
          description: Number of items per page returned in this list
          readOnly: true
          example: 10
        start_index:
          type: integer
          format: int64
          description: The offset into the entire list that this page starts at. Zero indexed
          readOnly: true
          example: 0
        total_results:
          type: integer
          format: int64
          description: The total number of items in the list
          readOnly: true
          example: 0
        items:
          type: array
          items:
            $ref: '#/components/schemas/companyOfficer'
    companyEFilingStatus:
      type: object
      readOnly: true
      required:
        - efiling_found_in_period
      properties:
        efiling_found_in_period:
          type: boolean
          description: Whether or not the company has eFiled any documents within the predefined period
          readOnly: true
          example: true
    actionCode:
      type: object
      readOnly: true
      required:
        - action_code
      properties:
        action_code:
          type: integer
          description: The current action code for the company
          readOnly: true
          example: 5000
    scottishBankruptOfficer:
      type: object
      required:
        - id
        - forename1
        - forename2
        - alias
        - surname
        - date_of_birth
        - address_line_1
        - address_line_2
        - address_line_3
        - town
        - county
        - postcode
        - case_reference
        - case_type
        - bankruptcy_type
        - start_date
        - debtor_discharge_date
        - trustee_discharge_date
      properties:
        id:
          type: string
          description: The id of the user
          readOnly: true
        forename1:
          type: string
          description: The officers' first name
          example: 
        forename2:
          type: string
          description: The officers' other forenames
          example: 
        alias:
          type: string
          description: The officers' alias/other name
          example: 
        surname:
          type: string
          description: The officers' surname
          example: 
        date_of_birth:
          type: string
          format: date
          description: The officers' date of birth details
          example: 2020-01-01
        address_line_1:
          type: string
          description: 
          example: 
        address_line_2:
          type: string
          description: 
          example: 
        address_line_3:
          type: string
          description: 
          example: 
        town:
          type: string
          description: 
          example: 
        county:
          type: string
          description: 
          example: 
        postcode:
          type: string
          description: 
          example: 
        case_reference: 
          type: string
          description: 
          example: 
        case_type: 
          type: string
          description: 
          example: 
        bankruptcy_type: 
          type: string
          description: 
          example: 
        start_date: 
          type: string
          format: date
          description: 
          example: 2020-01-01
        debtor_dischargeDate: 
          type: string
          description: 
          example: 
        trustee_dischargeDate: 
          type: string
          description: 
          example: 
    scottishBankruptOfficers:
      type: object
      required:
        - items_per_page
        - start_index
        - total_results
        - items
      properties:
        items_per_page:
          type: integer
          format: int64
          description: Number of items per page returned in this list
          readOnly: true
          example: 10
        start_index:
          type: integer
          format: int64
          description: The offset into the entire list that this page starts at. Zero indexed
          readOnly: true
          example: 0
        total_results:
          type: integer
          format: int64
          description: The total number of items in the list
          readOnly: true
          example: 0
        items:
          type: array
          items:
            $ref: '#/components/schemas/scottishBankruptOfficer'
  parameters:
    companyNumber:
      name: 'company_number'
      description: The company number
      in: 'path'
      required: true
      schema:
        type: string
      example: "12345678"
    officerId:
      name: 'officer_id'
      description: The id of the officer
      in: 'path'
      required: true
      schema:
        type: string
      example: "9876543210"
    startIndex:
      name: 'start_index'
      description: The offset into the entire list that this page starts at. Zero indexed
      in: 'query'
      required: false
      schema:
        type: integer
        format: int64
      example: "0"
    itemsPerPage:
      name: 'items_per_page'
      description: Number of items per page returned in this list
      in: 'query'
      required: false
      schema:
        type: integer
        format: int64
      example: "10"